# Generated by Django 4.2.1 on 2023-08-17 06:32

import courses.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('image', models.ImageField(upload_to='courses/advantages/images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'advantage',
                'verbose_name_plural': 'advantages',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.CharField(choices=[('JN', 'junior'), ('MD', 'middle'), ('SN', 'senior')], default='JN', max_length=2, verbose_name='complexity')),
                ('description', models.TextField(help_text='Enter a description', max_length=650, verbose_name='description')),
                ('title', models.CharField(blank=True, help_text='Enter the course title', max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('overview', models.CharField(blank=True, max_length=100, verbose_name='overview')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('image', models.ImageField(upload_to='courses/images/', verbose_name='image')),
                ('load', models.CharField(choices=[('LT', 'lite'), ('IS', 'intensive'), ('MR', 'moderate'), ('HG', 'high'), ('HH', 'highest')], default='LT', max_length=2, verbose_name='load')),
                ('period', models.PositiveSmallIntegerField(blank=True, help_text='Enter the training period', verbose_name='period')),
                ('count_projects', models.PositiveSmallIntegerField(blank=True, verbose_name='count projects')),
                ('price_per_mouth', models.PositiveIntegerField(blank=True, verbose_name='price per mouth')),
                ('price_immediately', models.PositiveIntegerField(blank=True, verbose_name='price immediately')),
                ('advantages', models.ManyToManyField(blank=True, related_name='courses', to='courses.advantage', verbose_name='advantages')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the subject title', max_length=50, verbose_name='title')),
                ('description', models.CharField(help_text='Enter a description of the subject', max_length=50, verbose_name='description')),
                ('image', models.ImageField(upload_to='subjects/images/', verbose_name='image')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('hints', models.TextField(verbose_name='hints')),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the module title', max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Enter a description of the module', verbose_name='description')),
                ('order', courses.fields.OrderField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a .webp image', upload_to='module/images/', verbose_name='image')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the lesson title', max_length=50, verbose_name='title')),
                ('order', courses.fields.OrderField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='module')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.technology', verbose_name='technologies'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('order', courses.fields.OrderField(blank=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module', verbose_name='module')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('additional_text', models.TextField(verbose_name='additional text')),
                ('status', models.CharField(blank=True, max_length=10, verbose_name='status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
            },
        ),
    ]
