# Generated by Django 4.2.1 on 2023-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default=0, help_text='Enter a description', max_length=600, verbose_name='description'),
            preserve_default=False,
        ),
    ]
