# Generated by Django 4.2.1 on 2023-08-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video_text_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
    ]
