# Generated by Django 4.2.1 on 2023-08-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_module_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a .webp image', upload_to='module/images/', verbose_name='image'),
        ),
    ]
