# Generated by Django 4.2.1 on 2023-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_description_alter_course_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='courses/technologies/images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Enter a description', max_length=650, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.CharField(max_length=100, verbose_name='overview'),
        ),
    ]
