# Generated by Django 4.2.1 on 2023-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_technology_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(related_name='courses', to='courses.technology', verbose_name='technologies'),
        ),
    ]
