# Generated by Django 4.2.1 on 2023-07-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(default=0, help_text='Enter a description of the subject', max_length=50, verbose_name='overview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default=0, upload_to='courses/images/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(help_text='Enter the subject title', max_length=50, verbose_name='title'),
        ),
    ]
