# Generated by Django 4.2.1 on 2023-07-11 12:36

import courses.validators.uploadimage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(upload_to='courses/technologies/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), courses.validators.uploadimage.validate_svg_image], verbose_name='image'),
        ),
    ]
