# Generated by Django 4.2.1 on 2023-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject_description_subject_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=0, upload_to='courses/images/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(help_text='Enter a description of the subject', max_length=50, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(upload_to='subjects/images/', verbose_name='image'),
        ),
    ]
