# Generated by Django 4.2.4 on 2023-09-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price_immediately',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_per_mouth',
        ),
    ]
