# Generated by Django 4.2.1 on 2023-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_image_alter_subject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='complexity',
            field=models.CharField(choices=[('JN', 'junior'), ('MD', 'middle'), ('SN', 'senior')], default='JN', max_length=2, verbose_name='complexity'),
        ),
    ]
