# Generated by Django 4.2.1 on 2023-07-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_technology_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='courses/advantages/images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'advantage',
                'verbose_name_plural': 'advantages',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AddField(
            model_name='course',
            name='advantages',
            field=models.ManyToManyField(related_name='courses', to='courses.advantage', verbose_name='technologies'),
        ),
    ]
