# Generated by Django 4.2.1 on 2023-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_advantage_remove_course_technologies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='advantages',
            field=models.ManyToManyField(related_name='courses', to='courses.advantage', verbose_name='advantages'),
        ),
    ]
