# Generated by Django 4.2.1 on 2023-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='hints',
            field=models.TextField(default=0, verbose_name='hints'),
            preserve_default=False,
        ),
    ]
