# Generated by Django 4.2.1 on 2023-07-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_technology_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='load',
            field=models.CharField(choices=[('LT', 'lite'), ('IS', 'intensive'), ('MR', 'moderate'), ('HG', 'high'), ('HH', 'highest')], default='LT', max_length=2, verbose_name='load'),
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.PositiveSmallIntegerField(default=0, help_text='Enter the training period', verbose_name='period'),
            preserve_default=False,
        ),
    ]
