# Generated by Django 4.2.1 on 2023-07-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_load_course_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count_projects',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='count projects'),
            preserve_default=False,
        ),
    ]
