# Generated by Django 4.2.1 on 2023-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_count_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(related_name='technology_list', to='courses.technology', verbose_name='technologies'),
        ),
    ]
