# Generated by Django 4.2.1 on 2023-07-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(related_name='courses', to='courses.technology', verbose_name='technologies'),
        ),
    ]
