# Generated by Django 4.2.1 on 2023-07-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_price_immediately_course_price_per_mouth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='advantages',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.advantage', verbose_name='advantages'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.card', verbose_name='cards'),
        ),
        migrations.AlterField(
            model_name='course',
            name='count_projects',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='count projects'),
        ),
        migrations.AlterField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.technology', verbose_name='technologies'),
        ),
    ]
