# Generated by Django 4.2.1 on 2023-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_card_course_alter_course_advantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='status'),
        ),
    ]
