# Generated by Django 4.2.1 on 2023-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, max_length=10, verbose_name='status'),
        ),
    ]
