# Generated by Django 4.2.1 on 2023-08-15 09:15

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_card_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the lesson title', max_length=50, verbose_name='title')),
                ('order', courses.fields.OrderField(blank=True)),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(help_text='Enter the module title', max_length=50, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(to='courses.lesson', verbose_name='lessons'),
        ),
    ]
