# Generated by Django 4.2.1 on 2023-08-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_lesson_alter_module_title_module_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='module'),
            preserve_default=False,
        ),
    ]
