# Generated by Django 4.2.1 on 2023-08-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_module_lessons_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a .webp image', upload_to='module_images/', verbose_name='image'),
        ),
    ]
