# Generated by Django 4.2.1 on 2023-05-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_countdown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countdown',
        ),
    ]
