# Generated by Django 4.2.1 on 2023-05-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
