# Generated by Django 4.2.1 on 2023-08-16 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('image', models.ImageField(upload_to='vookmarks/images/%Y/%m/%d/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создание')),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_created', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL, verbose_name='Понравилось')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='vookmarks_i_created_791589_idx'), models.Index(fields=['-total_likes'], name='vookmarks_i_total_l_fe28f5_idx')],
            },
        ),
    ]
