# Generated by Django 4.2.1 on 2023-05-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vookmarks', '0002_alter_image_users_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
