# Generated by Django 4.2.1 on 2023-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookmarks', '0003_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-total_likes'], name='vookmarks_i_total_l_fe28f5_idx'),
        ),
    ]
