# Generated by Django 4.2.1 on 2023-06-28 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 6, 28, 10, 12, 49, 150797, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 6, 28, 10, 14, 7, 386210, tzinfo=datetime.timezone.utc), unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 6, 28, 10, 14, 11, 466449, tzinfo=datetime.timezone.utc), max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='shop_catego_name_289c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'),
        ),
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
        migrations.DeleteModel(
            name='ProductTranslation',
        ),
    ]
