# Generated by Django 4.2.4 on 2023-09-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_email_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
